[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "dbwarden-pgsql-types"
version = "0.2.1"
description = "PostgreSQL custom types management for dbwarden"
readme = "README.md"
requires-python = ">=3.12.7"
dependencies = ["dbwarden>=0.16.0"]

[project.urls]
Homepage = "https://github.com/dbwarden-org/dbwarden-pgsql-types"
Source = "https://github.com/dbwarden-org/dbwarden-pgsql-types"

[project.entry-points."dbwarden.plugins"]
pgsql_types = "dbwarden_pgsql_types:setup"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest",
    "pytest-cov",
]
